version: '3.1'

volumes:
  node_backend:
  node_frontend:
  
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.production
    restart: always
    environment:
      PORT: "5000"
      DB_HOST: "$DB_HOST"
      DB_PORT: "$DB_PORT"
      DB_TYPE: "$DB_TYPE"
      DB_USER: "$DB_USER"
      DB_NAME: "$DB_NAME"
      DB_PASS: "$DB_PASS"
    volumes:
      - node_backend:/app/node_modules
    ports:
      - "5000"
  
  frontend_with_proxy:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.production
    restart: always
    volumes:
      - node_frontend:/app/node_modules
    ports:
      - "${PORT}:80"

