version: '3.1'

volumes:
  dependencies:
  
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.production
    restart: always
    environment:
      PORT: "$PORT"
      DB_HOST: "$DB_HOST"
      DB_PORT: "$DB_PORT"
      DB_TYPE: "$DB_TYPE"
      DB_USER: "$DB_USER"
      DB_NAME: "$DB_NAME"
      DB_PASS: "$DB_PASS"
    volumes:
      - node_backend:/app/node_modules
    ports:
      - "${PORT}:${PORT}"
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.production
    restart: always
    environment:
      PORT: "80"
    volumes:
      - node_frontend:/app/node_modules
    ports:
      - "80:80"

