version: '3.1'

volumes:
  dependencies:
  
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.production
    restart: always
    environment:
      PORT: "$PORT"
      DB_HOST: "$DB_HOST"
      DB_PORT: "$DB_PORT"
      DB_TYPE: "$DB_TYPE"
      DB_USER: "$DB_USER"
      DB_NAME: "$DB_NAME"
      DB_PASS: "$DB_PASS"
    volumes:
      - dependencies:/app/node_modules
    ports:
      - "${PORT}:${PORT}"

