version: 2.1
jobs:
  build-backend:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: cd Backend
      - run: npm install
      - run: npm run build

  build-frontend:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: echo "OK"

  test-backend:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: echo "OK"

  test-frontend:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - run: echo "OK"

  deploy:
    docker:
      - image: cimg/node:18.16
    steps:
      - run: sudo apt update
      - run: sudo apt-get install rsync
      # adds ssh keys from circleci
      - add_ssh_keys
      # copies files from repo to docker
      - checkout
      - run: cmd="DB_USER=$DB_USER ; DB_PASS=$DB_PASS ; DB_NAME=$DB_NAME; DB_PORT=$DB_PORT"
      - run: echo "$cmd"
      - run: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc --delete . $VPS_USER@$VPS_URL:~/projects/url_shortener
      - run: ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_URL "$cmd ; cd ~/projects/url_shortener && docker-compose -f docker-compose.prod.yaml up -d"
workflows:
  build-and-deploy:
    jobs:
      - deploy